controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Advert;
use app\models\AdvertForm;
use app\models\Category;
use app\models\LoginForm;
use app\models\PhotoForm;
use igogo5yo\uploadfromurl\UploadFromUrl;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AdminController extends Controller
{
    public $layout = 'admin';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'index', 'edit', 'upload', 'delete'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'edit', 'upload', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $query = Advert::find()
                    ->where(['checked' => false]);
        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
        ]);
        $adverts = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('adverts', 'pages'));
    }

    public function actionEdit($id)
    {
        $advert = Advert::find()
                    ->where(['id' => $id, 'checked' => false])
                    ->one();

        if (is_null($advert)) {
            return $this->redirect(['admin/index']);
        }

        $model = new AdvertForm();
        $model->setAdvert($advert);
        $categoryList = Category::selectDataProvider();
        $photos = $advert->getPhotos();

        if ($model->load(Yii::$app->request->post()) && $model->saveAndCheck()) {
            return $this->redirect(['admin/index']);
        }

        return $this->render('edit', compact('advert', 'model',
            'categoryList', 'photos'));
    }

    public function actionUpload($id, $url)
    {
        $advert = Advert::find()
                    ->where(['id' => $id, 'checked' => false])
                    ->one();

        if (is_null($advert)) {
            return $this->redirect(['admin/index']);
        }

        $model = new PhotoForm(['id' => $id, 'scenario' => 'url']);
        $model->imageFile = UploadFromUrl::initWithUrl($url);
        $model->upload();

        return $this->redirect(['admin/edit', 'id' => $id]);
    }

    public function actionDelete($id)
    {
        $advert = Advert::findOne($id);

        if (!is_null($advert)) {
            $advert->delete();
        }

        return $this->redirect(['admin/index']);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['admin/index']);
    }
}

views/admin/edit.php
<?php

/* @var $this yii\web\View */
/* @var $photos array */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Редактирование объявления';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-index">

    <div class="body-content">

        <h1><?= $this->title ?></h1>
        <p>&nbsp;</p>
        <? $form = ActiveForm::begin([
            'id' => 'project-form',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-sm-4\">{input}</div>\n<div class=\"col-lg-4\">{error}</div>",
            ],
        ]); ?>

            <div class="row">
                <div class="col-sm-offset-3 col-sm-9">
                    <div class="row">
                        <h3>Загруженные фото</h3>
                        <? if (count($photos) > 0):
                            /** @var app\models\Photo $photo */
                            foreach ($photos as $photo): ?>
                                <div class="thumbnail col-md-2">
                                    <img src="<?= $photo->getThumbUrl() ?>">
                                </div>
                            <? endforeach;
                        else: ?>
                            <p>Загруженных фото нет</p>
                        <? endif; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-3 col-sm-9">
                    <h3>Фото для загрузки</h3>
                    <div class="row" id="photos"></div>
                </div>
            </div>

            <?= $form->field($model, 'title')
                ->textInput() ?>

            <?= $form->field($model, 'cost')
                ->textInput(['min' => 0, 'type' => 'number']) ?>

            <?= $form->field($model, 'category_id')->dropDownList($categoryList) ?>

            <?= $form->field($model, 'description')
                ->textarea(['cols' => 30, 'rows' => 10]) ?>

            <?= $form->field($model, 'contact_name')
                ->textInput() ?>

            <?= $form->field($model, 'contact_email')
                ->textInput() ?>

            <?= $form->field($model, 'contact_phone')
                ->textInput() ?>

            <?= $form->field($model, 'contact_vk')
                ->textInput() ?>

            <div class="row">
                <div class="col-sm-offset-3">
                    <?= Html::submitButton('Сохранить и проверить', ['class' => 'btn btn-primary', 'name' => 'add-project']) ?>
                    <?= Html::a('Удалить', ['admin/delete', 'id' => $advert->id]) ?>
                </div>
            </div>

        <? ActiveForm::end(); ?>
    </div>
</div>
<script src="https://vk.com/js/api/openapi.js?157" type="text/javascript"></script>
<script>
    function init() {
        var name = document.getElementById('advertform-contact_name'),
            description = document.getElementById('advertform-description'),
            vk = document.getElementById('advertform-contact_vk'),
            photos = document.getElementById('photos');

        if (description.innerHTML.length > 0) {
            var text = description.innerHTML,
                match = null;

            if (match = text.match(/author_id:(\d+)/)) {
                description.innerHTML = text = text.replace(match[0] + "\n", '');
                var vk_id = match[1];
                VK.Api.call('users.get', { user_ids:vk_id, v:"5.73" }, function(result) {
                    if (!result.response) {
                        return;
                    }

                    var first_name = result.response[0].first_name,
                        last_name = result.response[0].last_name;

                    name.value = (first_name + ' ' + last_name).trim();

                    if (match = text.match(/post_id:(\d+)/)) {
                        description.innerHTML = text = text.replace(match[0] + "\n", '');
                        VK.Api.call('wall.getById', { posts: vk_id + '_' + match[1], v: '5.73' }, function(result) {
                            if (result.response.length > 0) {
                                vk.value = 'https://vk.com/wall' + vk_id + '_' + match[1];
                            } else {
                                vk.value = 'удалён';
                            }
                        });
                    }

                    description.innerHTML = text = text.trim();
                });
            }

            if (match = text.match(/photo:(.+)/ig)) {
                match.forEach(function (photo, index, arr) {
                    description.innerHTML = text = text.replace(photo + "\n", '');
                    photo = photo.replace('photo:', '');
                    url = '<?= Url::to(['admin/upload', 'id' => $advert->id, 'url' => 'url']) ?>';
                    url = url.substr(0, url.length - 3) + photo;
                    photos.innerHTML += '<a href="' + url + '" class="thumbnail col-md-2">\n' +
                    '    <img src="' + photo + '">\n' +
                    '</a>';
                });
            }

            description.innerHTML = text = text.trim();
        }
    }

    VK.init({
        apiId: 6632651
    });
    init();
</script>

views/admin/index.php
<?php

/* @var $this yii\web\View */
/* @var $adverts array */
/* @var $pages \yii\data\Pagination */

use yii\helpers\StringHelper;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$this->title = 'Непроверенные объявления';

?>
<div class="site-index">

    <div class="body-content">

        <h1><?= $this->title ?></h1>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>Описание</th>
                <th width="100">Действия</th>
            </tr>
            </thead>
            <tbody>
            <? if (count($adverts) > 0):
               /** @var app\models\Advert $advert */
               foreach($adverts as $advert): ?>
                    <tr>
                        <td><a href="<?= Url::to(['admin/edit', 'id' => $advert->id]) ?>" class="btn btn-link"><?= StringHelper::truncate($advert->getAdminDescription(), 100) ?></a></td>
                        <td>
                            <a href="<?= Url::to(['admin/delete', 'id' => $advert->id]) ?>" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </td>
                    </tr>
                <? endforeach; ?>
            <? else: ?>
                <tr>
                    <td colspan="2">
                        <p>Нет непроверенных объявлений.</p>
                    </td>
                </tr>
            <? endif; ?>
            </tbody>
        </table>

        <?= LinkPager::widget([
            'pagination' => $pages,
        ]) ?>

    </div>
</div>

views/admin/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email')->label('E-mail:')->textInput(['autofocus' => true, 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'password')->label('Пароль:')->passwordInput(['autocomplete' => 'off']) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Вход', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>