controllers/AdminController.php
<?php

namespace app\controllers;

use app\models\Advert;
use app\models\AdvertForm;
use app\models\Category;
use app\models\LoginForm;
use app\models\PhotoForm;
use igogo5yo\uploadfromurl\UploadFromUrl;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AdminController extends Controller
{
    public $layout = 'admin';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'index', 'edit', 'upload', 'delete'],
                'rules' => [
                    [
                        'actions' => ['logout', 'index', 'edit', 'upload', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $query = Advert::find()
                    ->where(['checked' => false]);
        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
        ]);
        $adverts = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', compact('adverts', 'pages'));
    }

    public function actionEdit($id)
    {
        $advert = Advert::find()
                    ->where(['id' => $id, 'checked' => false])
                    ->one();

        if (is_null($advert)) {
            return $this->redirect(['admin/index']);
        }

        $model = new AdvertForm();
        $model->setAdvert($advert);
        $categoryList = Category::selectDataProvider();
        $photos = $advert->getPhotos();

        if ($model->load(Yii::$app->request->post()) && $model->saveAndCheck()) {
            return $this->redirect(['admin/index']);
        }

        return $this->render('edit', compact('advert', 'model',
            'categoryList', 'photos'));
    }

    public function actionUpload($id, $url)
    {
        $advert = Advert::find()
                    ->where(['id' => $id, 'checked' => false])
                    ->one();

        if (is_null($advert)) {
            return $this->redirect(['admin/index']);
        }

        $model = new PhotoForm(['id' => $id, 'scenario' => 'url']);
        $model->imageFile = UploadFromUrl::initWithUrl($url);
        $model->upload();

        return $this->redirect(['admin/edit', 'id' => $id]);
    }

    public function actionDelete($id)
    {
        $advert = Advert::findOne($id);

        if (!is_null($advert)) {
            $advert->delete();
        }

        return $this->redirect(['admin/index']);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/index']);
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['admin/index']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Advert;
use app\models\Category;
use Yii;
use app\models\SearchForm;
use yii\data\Pagination;
use yii\web\Controller;
use yii\helpers\Url;

class SiteController extends Controller
{
    public function actionError()
    {
        return $this->render('error');
    }

    public function actionIndex()
    {
        $model = new SearchForm();

        return $this->render('index', compact('model'));
    }

    public function actionRules()
    {
        return $this->render('rules');
    }

    public function actionAboutUs()
    {
        return $this->render('about-us');
    }

    public function actionContacts()
    {
        return $this->render('contacts');
    }

    public function actionSearch()
    {
        $this->layout = 'search';
        $model = new SearchForm();
        $query = Advert::find();
        $categoryList = Category::selectDataProvider();

        Url::remember('', 'backUrl');

        if ($model->load(Yii::$app->request->get())) {
            $model->search($query);
        }

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => Yii::$app->params['searchPageSize'],
        ]);

        $adverts = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $paginationLinks = $pages->getLinks();

        return $this->render('search', compact('model', 'adverts',
            'paginationLinks', 'categoryList'));
    }
}

views/layouts/admin.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AdminAsset;

$this->registerLinkTag([
    'rel' => 'icon',
    'type' => 'image/x-icon',
    'href' => '/favicon.ico',
]);

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
    <?php $this->beginBody() ?>

    <div class="wrap">
        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl' =>
                Yii::$app->user->isGuest ? (
                    ['site/index']
                ) : (
                    ['admin/index']
                ),
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Главная', 'url' => ['/admin/index']],
                Yii::$app->user->isGuest ? (
                ['label' => 'Вход', 'url' => ['/admin/login']]
                ) : (
                    '<li>'
                    . Html::beginForm(['/admin/logout'], 'post')
                    . Html::submitButton(
                        'Выход',
                        ['class' => 'btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
                )
            ],
        ]);
        NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                'homeLink' => [
                    'label' => 'Главная',
                    'url' => ['admin/index'],
                ],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; <?= Yii::$app->name ?> <?= date('Y') ?></p>

            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>

views/layouts/advert.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\DetailAsset;

DetailAsset::register($this);

$this->title = Yii::$app->name;

if (!isset($this->description)) {
    $description = Yii::$app->params['defaultDescription'];
}

$this->registerMetaTag([
    'name' => 'description',
    'content' => $description,
]);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter49794901 = new Ya.Metrika2({ id:49794901, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/49794901" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" href="/images/logo/16x16.png" type="image/png">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo/57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo/72x72.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo/60x60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo/76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo/114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo/120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo/144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo/152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/180x180.png">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="profile">
    <?= $content ?>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\PageAsset;

PageAsset::register($this);

$this->title = Yii::$app->name;

if (!isset($this->description)) {
    $description = Yii::$app->params['defaultDescription'];
}

$this->registerMetaTag([
    'name' => 'description',
    'content' => $description,
]);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter49794901 = new Ya.Metrika2({ id:49794901, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/49794901" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" href="/images/logo/16x16.png" type="image/png">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo/57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo/72x72.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo/60x60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo/76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo/114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo/120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo/144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo/152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/180x180.png">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="page">
    <div class="container page__container">
        <div class="logo container__logo">
            <img class="logo__picture" src="/images/logo.png" alt="<?= Yii::$app->name ?> logo">
            <a class="link logo__title" href="<?= Yii::$app->homeUrl ?>"><?= Yii::$app->name ?></a>
        </div>
        <?= $content ?>
        <ul class="menu menu_align_center menu_distance_large container__menu">
            <li class="menu__link"><a class="link" href="<?= Url::to(['site/rules']) ?>">Правила</a></li>
            <li class="menu__link"><a class="link" href="<?= Url::to(['site/about-us']) ?>">О сайте</a></li>
            <li class="menu__link"><a class="link" href="<?= Url::to(['site/contacts']) ?>">Контакты</a></li>
        </ul>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/search.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\ProfileAsset;

ProfileAsset::register($this);

$this->title = Yii::$app->name;

if (!isset($this->description)) {
    $description = Yii::$app->params['defaultDescription'];
}

$this->registerMetaTag([
    'name' => 'description',
    'content' => $description,
]);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter49794901 = new Ya.Metrika2({ id:49794901, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://cdn.jsdelivr.net/npm/yandex-metrica-watch/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/49794901" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="icon" href="/images/logo/16x16.png" type="image/png">
    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo/57x57.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo/72x72.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo/60x60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo/76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo/114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo/120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo/144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo/152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/180x180.png">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="profile">
    <?= $content ?>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>