controllers/AdvertController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AdvertForm;
use app\models\Category;
use app\models\Advert;
use app\models\PhotoForm;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

class AdvertController extends AbstractController
{
    public function actionIndex($id)
    {
        $this->layout = 'advert';
        $backUrl = Url::previous('backUrl');
        $advert = Advert::findCheckedOne($id);

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if (is_null($backUrl)) {
            $backUrl = Url::to(['site/search']);
        }

        $canEdit = $this->hasPermissions($advert);
        $photos = $advert->getPhotos();
        $photoModel = new PhotoForm();

        return $this->render('index', compact('backUrl', 'advert',
            'canEdit', 'photos', 'photoModel'));
    }

    public function actionCreate()
    {
        $edit = false;
        $this->view->title = 'Подать объявление';
        $model = new AdvertForm(['scenario' => 'create']);
        $categoryList = Category::selectDataProvider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->addEditHash($model->getAdvert()->edit_hash);

            return $this->redirect(['advert/index', 'id' => $model->getAdvert()->id]);
        }

        return $this->render('create', compact('edit', 'model', 'categoryList'));
    }

    public function actionEdit($id, $edit_hash)
    {
        $edit = true;
        $this->view->title = 'Редактирование объявления';
        $advert = Advert::findOne(['id' => $id, 'edit_hash' => hex2bin($edit_hash)]);

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if (!$this->hasPermissions($advert)) {
            $this->addEditHash($advert->edit_hash);
        }

        $model = new AdvertForm(['scenario' => 'edit']);
        $model->setAdvert($advert);
        $categoryList = Category::selectDataProvider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['advert/index', 'id' => $advert->id]);
        }

        return $this->render('create', compact('edit', 'model', 'categoryList'));
    }

    public function actionDelete($id, $delete_hash, $confirm = false)
    {
        $this->view->title = 'Удаление объявления';
        $advert = Advert::findOne(['id' => $id, 'delete_hash' => hex2bin($delete_hash)]);
        $error = false;

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if ($confirm) {
            if ($advert->delete()) {
                return $this->redirect(['site/index']);
            }

            $error = true;
        }

        return $this->render('delete', compact('advert', 'error'));
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Advert;
use app\models\Category;
use Yii;
use app\models\SearchForm;
use yii\data\Pagination;
use yii\web\Controller;
use yii\helpers\Url;

class SiteController extends Controller
{
    public function actionError()
    {
        return $this->render('error');
    }

    public function actionIndex()
    {
        $model = new SearchForm();

        return $this->render('index', compact('model'));
    }

    public function actionRules()
    {
        return $this->render('rules');
    }

    public function actionAboutUs()
    {
        return $this->render('about-us');
    }

    public function actionContacts()
    {
        return $this->render('contacts');
    }

    public function actionSearch()
    {
        $this->layout = 'search';
        $model = new SearchForm();
        $query = Advert::find();
        $categoryList = Category::selectDataProvider();

        Url::remember('', 'backUrl');

        if ($model->load(Yii::$app->request->get())) {
            $model->search($query);
        }

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => Yii::$app->params['searchPageSize'],
        ]);

        $adverts = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $paginationLinks = $pages->getLinks();

        return $this->render('search', compact('model', 'adverts',
            'paginationLinks', 'categoryList'));
    }
}

views/site/about-us.php
<?php

/* @var $this yii\web\View */

?>
<div class="article container__article">
    <h1 class="article__title">О сайте</h1>
    <p class="text article__paragraph">Проект KupiSev.ru был придуман в ноябре 2017 года. До этого я искал жильё через интернет и плевался от объявлений от агенств. Это побудило меня создать такую доску, где будут проверяться объявления и будет жёсткая модерация от агенств.</p>
    <p class="text article__paragraph">Помимо контента, мне не понравился дизайн весьма популярного местного сайта, который сделан в стиле 2000-х и никак не был заточен под мобильники.</p>
    <p class="text article__paragraph">Таким образом я поставил цель догнать и перегнать в посещаемости тот самый сайт, чтобы они задумались об удобстве пользования их детищем.</p>

    <h2 class="article__title">Состояние</h2>
    <p class="text article__paragraph">(июль 2018) доска наполняется объявлениями из соц. сетей</p>
</div>

views/site/contacts.php
<?php

/* @var $this yii\web\View */

?>
<div class="article container__article">
    <h1 class="article__title">Контакты</h1>
    <p class="text article__paragraph">Если вам есть что сказать или предложить, пишите на <a href="mailto:support@kupisev.ru" class="link">support@kupisev.ru</a>.</p>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

?>
<div class="article container__article">
    <h1 class="article__title">Страница не найдена</h1>
    <p class="text article__paragraph">Ошибка 404.</p>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\SearchForm */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<? $form = ActiveForm::begin([
    'action' => Url::to(['site/search']),
    'method' => 'GET',
    'options' => [
        'class' => 'search-form container__search-form',
    ],
    'fieldConfig' => [
        'template' => '{input}',
        'options' => [
            'tag' => false,
        ],
    ],
]); ?>

<?= $form->field($model, 'query')->textInput([
    'class' => 'textfield search-form__textfield',
    'placeholder' => 'продам мотоцикл',
    'autofocus' => true,
]) ?>

<a class="button search-form__button button_color_green" href="javascript:this.document.forms[0].submit();">
    <img class="icon button__icon" src="/images/magnifier.svg" alt="search button">
</a>

<? ActiveForm::end() ?>

<p class="text container__text">Сервис <a class="link" href="<?= Url::to(['site/index']) ?>"><?= Yii::$app->name ?></a> позволяет найти объявления о продаже товаров или услуг в г.Севастополь.</p>
<div class="block container__block">
    <a class="button button_color_red block__button" href="<?= Url::to(['advert/create']) ?>">Подать объявление</a>
</div>

views/site/rules.php
<?php

/* @var $this yii\web\View */

?>
<div class="article container__article">
    <h1 class="article__title">Правила</h1>
    <p class="text article__paragraph">Объявление не должно нарушать законы РФ.</p>
    <p class="text article__paragraph">Правила могут быть изменены в любой момент без уведомления.</p>
</div>

views/site/search.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\SearchForm */
/* @var $adverts array */
/* @var $paginationLinks array */
/* @var $categoryList array */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\data\Pagination;
use app\widgets\Form;

?>
<div class="profile__sidebar">
    <div class="profile__header">
        <?= Html::a(Yii::$app->name, ['site/index'], ['class' => 'profile__logo']) ?>
        <div class="profile__opener">
            <img class="icon" src="/images/magnifier.svg" alt="search form opener">
        </div>
    </div>
    <div class="profile__sidebar-container">
        <? $form = Form::begin([
            'action' => Url::to(['site/search']),
            'method' => 'GET',
            'options' => [
                'class' => 'form form_type_no-title',
            ],
        ]); ?>

        <?= $form->field($model, 'query')->textInput() ?>

        <?= $form->field($model, 'category_id')->dropDownList($categoryList) ?>

        <input class="button button_color_red button_width_full" type="submit" value="Поиск">

        <? Form::end(); ?>
    </div>
</div>
<div class="profile__content">
    <div class="list">
        <? if (count($adverts) > 0):
           /** @var app\models\Advert $advert */
           foreach ($adverts as $advert): ?>
        <a class="poster list__item" href="<?= Url::to(['advert/index', 'id' => $advert->id]) ?>">
            <img class="picture poster__picture" src="<?= $advert->getAvatarUrl() ?>">
            <div class="poster__content">
                <div class="poster__title"><?= $advert->title ?></div>
                <time class="poster__date"><?= Yii::$app->formatter->asDate($advert->created_at) ?></time>
                <div class="price poster__price"><?= Yii::$app->formatter->asCurrency($advert->cost) ?></div>
            </div>
        </a>
        <? endforeach; ?>
        <? if (count($paginationLinks) > 0): ?>
        <ul class="list__pagination menu menu_align_center">
            <? if (!empty($paginationLinks[Pagination::LINK_FIRST])): ?>
            <li class="menu__link">
                <a href="<?= $paginationLinks[Pagination::LINK_FIRST] ?>" class="link">Первая</a>
            </li>
            <? endif; ?>
            <? if (!empty($paginationLinks[Pagination::LINK_PREV])): ?>
            <li class="menu__link">
                <a href="<?= $paginationLinks[Pagination::LINK_PREV] ?>" class="link"><< Предыдущая</a>
            </li>
            <? endif; ?>
            <? if (!empty($paginationLinks[Pagination::LINK_NEXT])): ?>
            <li class="menu__link">
                <a href="<?= $paginationLinks[Pagination::LINK_NEXT] ?>" class="link">Следующая >></a>
            </li>
            <? endif; ?>
            <? if (!empty($paginationLinks[Pagination::LINK_LAST])): ?>
            <li class="menu__link">
                <a href="<?= $paginationLinks[Pagination::LINK_LAST] ?>" class="link">Последняя</a>
            </li>
            <? endif; ?>
        </ul>
        <? endif; ?>
        <? else: ?>
        <p class="text">По заданному запросу нет объявлений.</p>
        <? endif; ?>
    </div>
</div>