models/Advert.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\StringHelper;

/** @property int $id */
/** @property string $title */
/** @property string $description */
/** @property int $cost */
/** @property int $category_id */
/** @property string $edit_hash */
/** @property string $delete_hash */
/** @property string $contact_name */
/** @property string $updated_at */
/** @property string $created_at */
/** @property string $avatar */

class Advert extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function rules()
    {
        return [
            [['title', 'description', 'cost',
                'category_id', 'contact_name'], 'required'],
            ['title', 'string', 'max' => 60],
            [['id', 'cost', 'category_id'], 'integer', 'min' => 0],
            [['edit_hash', 'delete_hash'], 'string', 'length' => 32],
            ['avatar', 'string'],
        ];
    }

    public function beforeSave($insert)
    {
        if (!empty($this->edit_hash)) {
            $this->edit_hash = hex2bin($this->edit_hash);
        }

        if (!empty($this->delete_hash)) {
            $this->delete_hash = hex2bin($this->delete_hash);
        }

        if (!empty($this->avatar)) {
            $this->avatar = hex2bin($this->avatar);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!empty($this->edit_hash)) {
            $this->edit_hash = bin2hex($this->edit_hash);
        }

        if (!empty($this->delete_hash)) {
            $this->delete_hash = bin2hex($this->delete_hash);
        }

        if (!empty($this->avatar)) {
            $this->avatar = bin2hex($this->avatar);
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if (!empty($this->edit_hash)) {
            $this->edit_hash = bin2hex($this->edit_hash);
        }

        if (!empty($this->delete_hash)) {
            $this->delete_hash = bin2hex($this->delete_hash);
        }

        if (!empty($this->avatar)) {
            $this->avatar = bin2hex($this->avatar);
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getAvatarUrl($full = false)
    {
        $url = Yii::$app->params['defaultAvatar'];

        if (!empty($this->avatar)) {
            $url = Yii::$app->params['uploadsDir'] . $this->avatar . '.jpg';
        }

        if ($full) {
            $url = Yii::$app->urlManager->getHostInfo() . $url;
        }

        return $url;
    }

    public function getEmail()
    {
        $email = AdvertContact::findOne(['advert_id' => $this->id, 'type' => 'email']);

        if (is_null($email)) {
            $email = new AdvertContact();
            $email->advert_id = $this->id;
            $email->type = AdvertContact::TYPE_EMAIL;
        }

        return $email;
    }

    public function getPhone()
    {
        $phone = AdvertContact::findOne(['advert_id' => $this->id, 'type' => 'phone']);

        if (is_null($phone)) {
            $phone = new AdvertContact();
            $phone->advert_id = $this->id;
            $phone->type = AdvertContact::TYPE_PHONE;
        }

        return $phone;
    }

    public function getVk()
    {
        $phone = AdvertContact::findOne(['advert_id' => $this->id, 'type' => 'vk']);

        if (is_null($phone)) {
            $phone = new AdvertContact();
            $phone->advert_id = $this->id;
            $phone->type = AdvertContact::TYPE_VK;
        }

        return $phone;
    }

    public function getContacts()
    {
        return AdvertContact::find()
                ->where(['advert_id' => $this->id])
                ->all();
    }

    public function getPhotos()
    {
        return Photo::find()
                ->where(['advert_id' => $this->id])
                ->all();
    }

    public function delete()
    {
        $deps = array_merge($this->getContacts(), $this->getPhotos());

        /** @var ActiveRecord $dep */
        foreach ($deps as $dep) {
            $dep->delete();
        }

        return parent::delete();
    }

    public function getAdminDescription()
    {
        $pos = strpos($this->description, "\n\n");

        if (false === $pos) {
            return $this->description;
        }

        return StringHelper::byteSubstr($this->description, $pos);
    }

    public static function findCheckedOne($condition)
    {
        $query = self::findByCondition($condition);

        $query->andWhere(['checked' => true]);

        return $query->one();
    }
}

models/AdvertForm.php
<?php

namespace app\models;

use function foo\func;
use Yii;
use himiklab\yii2\recaptcha\ReCaptchaValidator;

class AdvertForm extends AbstractForm
{
    public $id;
    public $title;
    public $cost;
    public $category_id;
    public $description;
    public $contact_name;
    public $contact_email;
    public $contact_phone;
    public $contact_vk;
    public $reCaptcha;

    private $_advert;

    public function attributeLabels()
    {
        return [
            'title' => 'Заголовок объявления',
            'cost' => 'Стоимость в рублях',
            'category_id' => 'Категория объявления',
            'description' => 'Описание объявления',
            'contact_name' => 'Как вас зовут?',
            'contact_email' => 'Контактный E-mail',
            'contact_phone' => 'Контактный телефон',
            'contact_vk' => 'Ссылка в VK',
        ];
    }

    public function rules()
    {
        return [
            [['title', 'cost', 'category_id', 'description',
                'contact_name'], 'required'],
            [['contact_email', 'contact_phone'], 'required',
                'on' => ['create', 'edit']],
            [['title', 'cost', 'description', 'contact_name',
                'contact_email', 'contact_phone'], 'trim'],
            ['title', 'string', 'max' => 60],
            ['contact_email', 'email'],
            ['contact_phone', 'udokmeci\yii2PhoneValidator\PhoneValidator',
                'country' => 'RU'],
            [['id', 'cost'], 'integer', 'min' => 0],
            ['category_id', 'checkCategoryId', 'params' => ['strict' => true]],
            [['reCaptcha'], ReCaptchaValidator::class,
                'uncheckedMessage' => 'Похоже вы робот :) Нажмите на галочку ещё раз',
                'on' => ['create']],
            ['contact_vk', 'url'],
        ];
    }

    public function save()
    {
        if (!$this->validate()) {
            return false;
        }

        $advert = $this->getAdvert();
        $advert->title = $this->title;
        $advert->cost = $this->cost;
        $advert->category_id = $this->category_id;
        $advert->description = $this->description;
        $advert->contact_name = $this->contact_name;

        if (empty($this->id)) {
            $advert->edit_hash = bin2hex(random_bytes(16));
            $advert->delete_hash = bin2hex(random_bytes(16));
            $advert->checked = Yii::$app->params['checkAfterCreate'];
        }

        if (!$advert->save()) {
            return false;
        }

        if (is_null($advert->avatar)) {
            $photos = $advert->getPhotos();

            if (count($photos) > 0) {
                $advert->avatar = $photos[0]->name;
            }

            $advert->save();
        }

        $id = $advert->id;
        $contact_name = $advert->contact_name;
        $edit_hash = $advert->edit_hash;
        $delete_hash = $advert->delete_hash;

        if (!empty($this->contact_email)) {
            $email = $advert->getEmail();
            $email->value = $this->contact_email;

            if (!$email->save()) {
                return false;
            }
        }

        if (!empty($this->contact_phone)) {
            $phone = $advert->getPhone();
            $phone->value = $this->contact_phone;

            if (!$phone->save()) {
                return false;
            }
        }

        if (!empty($this->contact_vk)) {
            $vk = $advert->getVk();
            $vk->value = $this->contact_vk;

            if (!$vk->save()) {
                return false;
            }
        }

        if (is_null($this->id)) {
            /** @var \nterms\mailqueue\Message $mail */
            $mail = Yii::$app->mailqueue->compose('create_advert', compact(
                'id',
                'contact_name',
                'edit_hash',
                'delete_hash'
            ));

            $mail->setFrom(Yii::$app->params['noreplyEmail'])
                 ->setTo($this->contact_email)
                 ->setSubject('Управление созданным объявлением');

            return $mail->queue();
        }

        return true;
    }

    public function saveAndCheck()
    {
        if (!$this->save()) {
            return false;
        }

        $advert = $this->getAdvert();

        $advert->checked = true;

        return $advert->save();
    }

    /** @var \app\models\Advert $advert */
    public function setAdvert($advert)
    {
        $this->_advert = $advert;
        $this->id = $advert->id;
        $this->title = $advert->title;
        $this->cost = $advert->cost;
        $this->category_id = $advert->category_id;
        $this->description = $advert->description;
        $this->contact_name = $advert->contact_name;
        $this->contact_email = $advert->getEmail()->value;
        $this->contact_phone = $advert->getPhone()->value;
    }

    public function getAdvert()
    {
        if (empty($this->_advert)) {
            $this->_advert = Advert::findOne($this->id);

            if (is_null($this->_advert)) {
                $this->_advert = new Advert();
            } else {
                $this->id = $this->_advert->id;
            }
        }

        return $this->_advert;
    }
}

controllers/AdvertController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AdvertForm;
use app\models\Category;
use app\models\Advert;
use app\models\PhotoForm;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

class AdvertController extends AbstractController
{
    public function actionIndex($id)
    {
        $this->layout = 'advert';
        $backUrl = Url::previous('backUrl');
        $advert = Advert::findCheckedOne($id);

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if (is_null($backUrl)) {
            $backUrl = Url::to(['site/search']);
        }

        $canEdit = $this->hasPermissions($advert);
        $photos = $advert->getPhotos();
        $photoModel = new PhotoForm();

        return $this->render('index', compact('backUrl', 'advert',
            'canEdit', 'photos', 'photoModel'));
    }

    public function actionCreate()
    {
        $edit = false;
        $this->view->title = 'Подать объявление';
        $model = new AdvertForm(['scenario' => 'create']);
        $categoryList = Category::selectDataProvider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->addEditHash($model->getAdvert()->edit_hash);

            return $this->redirect(['advert/index', 'id' => $model->getAdvert()->id]);
        }

        return $this->render('create', compact('edit', 'model', 'categoryList'));
    }

    public function actionEdit($id, $edit_hash)
    {
        $edit = true;
        $this->view->title = 'Редактирование объявления';
        $advert = Advert::findOne(['id' => $id, 'edit_hash' => hex2bin($edit_hash)]);

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if (!$this->hasPermissions($advert)) {
            $this->addEditHash($advert->edit_hash);
        }

        $model = new AdvertForm(['scenario' => 'edit']);
        $model->setAdvert($advert);
        $categoryList = Category::selectDataProvider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['advert/index', 'id' => $advert->id]);
        }

        return $this->render('create', compact('edit', 'model', 'categoryList'));
    }

    public function actionDelete($id, $delete_hash, $confirm = false)
    {
        $this->view->title = 'Удаление объявления';
        $advert = Advert::findOne(['id' => $id, 'delete_hash' => hex2bin($delete_hash)]);
        $error = false;

        if (is_null($advert)) {
            throw new NotFoundHttpException();
        }

        if ($confirm) {
            if ($advert->delete()) {
                return $this->redirect(['site/index']);
            }

            $error = true;
        }

        return $this->render('delete', compact('advert', 'error'));
    }
}

controllers/PhotoController.php
<?php

namespace app\controllers;

use app\models\Photo;
use app\models\PhotoForm;
use Yii;
use app\models\Advert;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

class PhotoController extends AbstractController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'upload' => ['post'],
                ],
            ],
        ];
    }

    public function actionUpload($id)
    {
        $advert = Advert::findOne($id);

        if (is_null($advert)) {
            return $this->redirect(['site/index']);
        }

        if (!$this->hasPermissions($advert)) {
            return $this->redirect(['advert/index', 'id' => $id]);
        }

        if (Yii::$app->request->isPost) {
            $model = new PhotoForm(['id' => $advert->id, 'scenario' => 'file']);
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            $model->upload();
        }

        return $this->redirect(['advert/index', 'id' => $id]);
    }

    public function actionDelete($id, $photo_id)
    {
        $advert = Advert::findOne($id);
        $photo = Photo::findOne(['advert_id' => $id, 'id' => $photo_id]);

        if (is_null($advert) || is_null($photo)) {
            return $this->redirect(['site/index']);
        }

        if (!$this->hasPermissions($advert)) {
            return $this->redirect(['advert/index', 'id' => $id]);
        }

        $photo->delete();

        return $this->redirect(['advert/index', 'id' => $id]);
    }
}

views/advert/create.php
<?php

/* @var $this yii\web\View */
/* @var $edit boolean */
/* @var $model \app\models\AdvertForm */
/* @var $categoryList array */

use app\widgets\Form;
use yii\helpers\Url;
use himiklab\yii2\recaptcha\ReCaptcha;

?>
<div class="article container__article">
    <h1 class="article__title"><?= $this->title ?></h1>
    <? $form = Form::begin() ?>

        <?= $form->field($model, 'title')
                 ->textInput() ?>

        <?= $form->field($model, 'cost')
                 ->textInput(['min' => 0, 'type' => 'number']) ?>

        <?= $form->field($model, 'category_id')->dropDownList($categoryList) ?>

        <?= $form->field($model, 'description')
                 ->textarea(['cols' => 30, 'rows' => 10]) ?>

        <?= $form->field($model, 'contact_name')
                 ->textInput() ?>

        <?= $form->field($model, 'contact_email')
                 ->textInput() ?>

        <?= $form->field($model, 'contact_phone')
                 ->textInput() ?>

        <? if (!$edit): ?>
        <?= $form->field($model, 'reCaptcha')->widget(ReCaptcha::class)
                 ->label(false) ?>
        <? endif; ?>

        <? if ($edit): ?>
            <input class="button button_color_red form__button" type="submit" value="Сохранить объявление">
            <a class="button button_align_right form__button" href="<?= Url::to(['advert/index', 'id' => $model->getAdvert()->id]) ?>">Назад</a>
        <? else: ?>
            <p class="text form__text">Нажимая кнопку "Создать объявление" вы соглашаетесь с <a class="link" href="/rules" target="_blank">правилами сайта</a>.</p>
            <input class="button button_color_red form__button" type="submit" value="Создать объявление">
            <input class="button button_align_right form__button" type="reset" value="Очистить форму">
        <? endif; ?>
    <? Form::end(); ?>
</div>

views/advert/delete.php
<?php

/* @var $this yii\web\View */
/* @var $advert app\models\Advert */
/* @var $error boolean */

use yii\helpers\Url;

?>
<div class="article container__article">
    <h1 class="article__title">Удалить объявление</h1>
    <? if ($error): ?>
    <p class="text article__paragraph">Не удалось удалить объявление...</p>
    <p class="text article__paragraph"><a href="<?= Url::to(['advert/index',
            'id' => $advert->id]) ?>" class="link">Назад</a></p>
    <? else: ?>
    <p class="text article__paragraph">Вы уверены, что хотите удалить объявление?</p>
    <div class="article__button-group">
        <a class="button button_color_red" href="<?= Url::to(['advert/delete',
            'id' => $advert->id, 'delete_hash' => $advert->delete_hash,
            'confirm' => true]) ?>">Удалить</a>
        <a class="button button_align_right" href="<?= Url::to(['advert/index',
            'id' => $advert->id]) ?>">Назад</a>
    </div>
    <? endif; ?>
</div>

views/advert/index.php
<?php

/* @var $this yii\web\View */
/* @var $backUrl string */
/* @var $advert app\models\Advert */
/* @var $canEdit boolean */
/* @var $photos array */
/* @var $photoModel app\models\PhotoForm */

use yii\helpers\Html;
use yii\helpers\Url;
use app\widgets\ContactWidget;
use app\widgets\ShareWidget;
use app\widgets\Form;

?>
<div class="profile__sidebar">
    <div class="profile__header">
        <a class="profile__logo" href="<?= $backUrl ?>">Поиск</a>
        <div class="profile__opener">
            <img class="icon" src="/images/phone-white.svg" alt="contact block opener">
        </div>
    </div>
    <div class="profile__sidebar-container">
        <div class="contact">
            <img class="picture contact__picture" src="/images/img_avatar3.png" alt="фото пользователя">
            <div class="contact__info">
                <div class="contact__name"><?= $advert->contact_name ?></div>
                <?= ContactWidget::widget(['dataProvider' => $advert->getContacts()]) ?>
            </div>
        </div>
    </div>
</div>

<div class="poster-detail profile__poster-detail">
    <h1 class="poster-detail__title"><?= $advert->title ?></h1>
    <time class="poster-detail__date">Размещено <?= Yii::$app->formatter->asDate($advert->created_at) ?></time>
    <div class="price poster-detail__price"><?= Yii::$app->formatter->asCurrency($advert->cost) ?></div>

    <h2 class="poster-detail__small-title">Описание автора</h2>
    <p class="text poster-detail__text"><?= nl2br(Html::encode($advert->description)) ?></p>

    <h2 class="poster-detail__small-title">Поделиться</h2>
    <?= ShareWidget::widget([
        'title' => $advert->title,
        'url' => Url::to(['advert/index', 'id' => $advert->id], true),
        'picture' => empty($advert->avatar) ? null : $advert->getAvatarUrl(true),
    ]) ?>

    <? if ($canEdit): ?>
    <h2 class="poster-detail__small-title">Управление объявлением</h2>
    <p class="text poster-detail__text">
        <a class="button button_color_blue" href="<?= Url::to(['advert/edit', 'id' => $advert->id, 'edit_hash' => $advert->edit_hash]) ?>">Редактировать</a>
        <a class="button button_color_red" href="<?= Url::to(['advert/delete', 'id' => $advert->id, 'delete_hash' => $advert->delete_hash]) ?>">Удалить</a>
    </p>
    <? endif; ?>
</div>

<div class="gallery profile__gallery">
    <div class="gallery__title">Фото</div>
    <? if ($canEdit): ?>
        <a href="#" class="button button_color_green add-image">Добавить</a>
        <? $form = Form::begin([
            'action' => Url::to(['photo/upload', 'id' => $advert->id]),
            'options' => [
                'class' => 'file-upload gallery__form',
            ],
            'fieldConfig' => [
                'template' => '{input}',
                'options' => [
                    'class' => null,
                ],
            ],
        ]); ?>
        <?= $form->field($photoModel, 'imageFile')
                 ->label(false)->fileInput(['id' => 'file_pic']) ?>
        <input type="hidden" name="MAX_FILE_SIZE" value="2097152">
        <input type="submit" id="file_submit">
        <? Form::end() ?>
    <? endif; ?>
    <div class="gallery__pictures">
        <? if (count($photos) > 0):
           /** @var app\models\Photo $photo */
           foreach ($photos as $photo): ?>
        <div class="gallery__picture">
            <a href="<?= $photo->getUrl() ?>" class="swipebox">
                <img class="picture" src="<?= $photo->getThumbUrl() ?>" >
            </a>
            <? if ($canEdit): ?>
            <a class="link link_only_icon gallery__delete" href="<?= Url::to(['photo/delete',
                'id' => $advert->id, 'photo_id' => $photo->id]) ?>">
                <img class="link__icon" src="/images/delete.svg" alt="delete button">
            </a>
            <? endif; ?>
        </div>
        <? endforeach;
           else: ?>
        <p class="text">Нет фото.</p>
        <? endif; ?>
    </div>
</div>